### ISSUE TITLE
clean more escape sequences

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [vaeth/logclean#2]
stuff like this `[32;01m * [39;49;00m` doesn't get cleaned
see https://gist.github.com/Alessandro-Barbieri/6628c59a3b60913627363bee10da599c
for an example

**Comment by vaeth** [comment]
Not reproducible; here, uncolor works. logclean relies on "colorstrip" from Term::ANSIColor for this which should be available with all current perl version. Maybe the one in your perl version is buggy (I am using perl-5.30.0 here.)
You can try triggering it explicitly with `logclean uncolor log-filename` (I do not remember, but I suppose the logfile still has to be uncompressed for this call).

**Comment by Alessandro-Barbieri** [comment]
I see. I tried manually and it works. Seems that the original .log file it's not uncolored.
I have now another question then, but i'll open a new issue.
