### ISSUE TITLE
in-place uncoloring

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [vaeth/logclean#3]
Is it possible to automatically uncolor the .log files and replace the original with the uncolored version?
I see that by default it uncolor and compress but the original stay as is (the original will be deleted later e.g. after 24 hours)

**Comment by vaeth** [comment]
I doubt that the default is to keep the original files. Perhaps you have specified the --older (-o) option in some alias or wrapper script. I would consider it a bad idea to modify files impacted by this option; the intention to keep these files for a while is that they might currently still be modified by a running emerge command, and modifying possibly changing files is wrong.

**Comment by Alessandro-Barbieri** [comment]
I see the point. Thanks
